FROM {{ image_spec("base-tools") }}
MAINTAINER {{ maintainer }}

{{ copy_sources("seecloud/availability", "/availability") }}

RUN pip install -r /availability/requirements.txt \
    && pip install --upgrade /availability
